version: "3"
services:
  app:
    build: .
    environment:
      - ENV=prod
      - WORKERS=4
    volumes:
      - data:/data
      - static:/static
    depends_on:
      - db
      - memcached

  db:
    image: postgres:11
    volumes:
      - pgdata:/var/lib/postgresql/data

  memcached:
    image: memcached:1.5

  nginx:
    build: nginx/
    volumes:
      - static:/static
      - logs:/logs
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  data:
  static:
  pgdata:
  logs: