version: "3"
services:
  app:
    build: .
    environment:
      - ENV=dev
    volumes:
      - .:/app
      - data:/data
      - static:/static
    ports:
      - 8000:8000
    command: ./manage.py runserver 0:8000
    depends_on:
      - db
      - memcached

  db:
    image: postgres:11-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  memcached:
    image: memcached:1.5-alpine

volumes:
  data:
  static:
  pgdata: