version: "3"
services:
  app:
    build: .
    environment:
      - ENV=test
    volumes:
      - data:/data
      - static:/static
    command: python manage.py runserver 0:8000
    depends_on:
      - db
      - memcached

  db:
    image: postgres:11-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data

  memcached:
    image: memcached:1.5-alpine

volumes:
  data:
  static:
  pgdata: