version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build test environment
          command: |
            docker-compose -f docker-compose-test.yml build
            docker-compose -f docker-compose-test.yml pull
      - run:
          name: Run unit tests
          command: docker-compose -f docker-compose-test.yml run app ./manage.py test
      - run:
          name: Test database migrations
          command: docker-compose -f docker-compose-test.yml run app ./manage.py migrate
      - run:
          name: Test fetching and updating SDE
          command: docker-compose -f docker-compose-test.yml run app ./manage.py updatesde

workflows:
  version: 2
  build_and_test:
    jobs:
      - test