version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker-compose -f docker-compose-test.yml run app pypy3 manage.py test
          docker-compose -f docker-compose-test.yml run app pypy3 manage.py migrate
          docker-compose -f docker-compose-test.yml run app pypy3 manage.py updatesde

workflows:
  version: 2
  build_and_test:
    jobs:
      - test